#image: nercury:cmake-cpp
before_script:
  - date
  - sudo apt-get install -y cmake g++
test:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./tree
build:
  script:
    - ./run
after_script:
  - date
