#image: nercury:cmake-cpp
#image: trusty:base
image: ubuntu:yakkety
before_script:
  - date
  - apt-get update -y
  - ./setup.sh
test:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make tree
    - ./tree
build:
  script:
    - ./run tree
after_script:
  - date
