#image: nercury:cmake-cpp
#image: trusty:base
image: ubuntu:yakkety
before_script:
  - date
  - apt-get update -y
  - ./setup.sh
test:
  script:
    - echo "Testing manual run in build folder"
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./unit_tests
    - echo "Now testing via runner script"
    - cd ..
    - ./run unit_tests
    - ./run all
build:
  script:
    - ./run tree
after_script:
  - date
