#image: nercury:cmake-cpp
#image: trusty:base
image: ubuntu:yakkety
before_script:
  - date
  - apt-get update -y
  - apt-get install -y cmake g++
test:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./tree
build:
  script:
    - ./run
after_script:
  - date
