#!/usr/bin/env bash
mkdir -p build
cd build
cmake ..
make # $@
if [[ $1 = 'exec' || $1 = 'e' || $1 = 'tree' ]]; then
  ./tree
elif [[ $1 = 'unit_tests' || $1 = 't' || $1 = 'test' || $1 = 'tests' ]]; then
  ./unit_tests
elif [[ $1 = 'a' || $1 = 'all' ]]; then
  ./unit_tests && ./tree
else
  echo "Executables build."
  echo "  Run using ./build/tree or ./build/unit_tests."
fi
